[package]
name = "nu-color-config"
version = "0.59.0"
edition = "2021"

[dependencies]
nu-protocol = { path = "../nu-protocol", version = "0.59.0"  }
# nu-ansi-term = { path = "../nu-ansi-term", version = "0.59.0"  }
nu-ansi-term = "0.42.0"

nu-json = { path = "../nu-json", version = "0.59.0"  }
nu-table = { path = "../nu-table", version = "0.59.0"  }

serde = { version="1.0.123", features=["derive"] }
